name: cycle_lock
description: Project for cycle storage

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  responsive_framework:
  location:
  lottie:
  flutter_credit_card:
  flutter_svg:
  country_code_picker:
  pin_code_fields:
  carousel_slider:
  animations:
  flutter_staggered_animations:
  fluttertoast:
  #table_calendar: ^2.3.3
  table_calendar: ^3.0.6
  intl:
  shared_preferences:
  dio:
  provider:
  date_util:
  image_picker:
  #  firebase_messaging: ^11.2.7
  cupertino_icons:
  google_maps_flutter:
  package_info_plus:
  flutter_native_splash:
  flutter_datetime_picker:
  device_calendar:
  url_launcher:
  persistent_bottom_nav_bar:
  calendar_date_picker2:
  smooth_star_rating:
  flutter_restart:
  firebase_auth:
  google_sign_in:
  firebase_messaging:
  firebase_core:
  dotted_border:
  firebase_analytics:
  flutter_local_notifications:
  flutter_facebook_auth:
  sign_in_with_apple:
  crypto:
  http:
  jiffy:
  geocoder:
  geolocator:
  easy_localization:
  dropdown_search: ^3.0.1
  flutter_share:
  path_provider:
  custom_info_window:
  clippy_flutter:
  video_player:
  awesome_notifications:
  flutter_js:
  sdk:
    path: /Users/inventcolabsamit/Downloads/FlutterLatest07122021/sdk
  curved_navigation_bar: ^1.0.3
  add_2_calendar: ^2.1.2
  calendar_view: ^0.0.5
  syncfusion_flutter_datepicker: ^18.4.49-beta
  flutter_multi_formatter: ^1.3.6
  timezone:
  geocoding:
  google_places_flutter:
  cached_network_image:
  #mask_text_input_formatter: ^1.2.1







dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/appLanguage/
    - assets/images/
    - assets/fonts/
    - assets/map_style.txt
    - assets/nointernet.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/dubai_bold.ttf
          weight: 700
        - asset: assets/fonts/dubai_light.ttf
          weight: 300
        - asset: assets/fonts/dubai_medium.ttf
          weight: 500
        - asset: assets/fonts/dubai_regular.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

